---
name: Check Rust

on: [push, pull_request, workflow_dispatch]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run fmt check
        run: cargo +nightly fmt --verbose -- --check

      - name: Run clippy check
        run: cargo clippy --all-targets --all-features -- -D warnings